/**
 * Catalog descriptions for the Retrieval op group. These strings are
 * documentation surfaced by `allDescriptions`, describing each op's typed
 * options, inputs, and outputs (see retrieve.ts).
 */

export const RetrieveOpDescription = `RetrieveOp: pulls the top-k documents most relevant to a query from a registered Retriever (RAG fan-in).
  Options:  k number — number of documents to return (default 5). Lower values keep prompts compact; higher values broaden recall.
            retrieverId string — selects a Retriever registered via registerRetriever (default "" → process default set via setDefaultRetriever).
            credentialRef string — opaque credential identifier installed on the retrieval context for the Retriever (default ""; consumed by vector-store-backed Retrievers via resolveEmbeddingClient; ignored by Retrievers that don't embed). credentialRef is a LOOKUP REFERENCE (e.g. an env-var name like "CLAUDE_API_KEY" or a factory key like "voyage-prod") that a registered EmbeddingClientFactory translates into a real credential — it is NOT the secret value itself. Never put an API key, OAuth token, vault URL, or any other secret material as the credentialRef value: such values would land verbatim in your committed source, get pushed to git, and end up indexed by every tool that reads the repo.
            clientFactoryId string — selects a registered EmbeddingClientFactory by id for the Retriever's embedding lookup (default "" → process default set via setDefaultEmbeddingClientFactory). NOTE: the bundled EnvEmbeddingClientFactory only supports provider="gemini". For any other embedding provider (Claude, OpenAI, Voyage, Cohere, …) you MUST register a custom factory via registerEmbeddingClientFactory (or setDefaultEmbeddingClientFactory) before running the graph — the default rejects unknown providers with an error. This is asymmetric with AI ops, whose bundled EnvAIClientFactory supports both Claude and Gemini.
            factoryTimeoutMs number — deadline for the EmbeddingClientFactory credential lookup in milliseconds (default 30000; 0 disables). Bounds the factory's credential-lookup leg only (Vault / Secrets Manager / KMS round trip); the subsequent Retriever.retrieve call is NOT covered by this budget.
            embedTimeoutMs number — wallclock deadline applied to the ENTIRE Retriever.retrieve call in milliseconds (embedding API call + vector search + post-filtering — whatever the Retriever does end-to-end). undefined / 0 = no per-op deadline (the call honors only the ambient signal). Wraps the retrieve invocation with an abort deadline; when it fires, the op returns the wrapped timeout error. Complementary to factoryTimeoutMs: factoryTimeoutMs caps the credential lookup, embedTimeoutMs caps the actual retrieval work.
  Input:    query string — the natural-language search query.
  Output:   documents Document[] — full records ({ id, content, score, metadata }) sorted best-first. Use when downstream ops need ids, scores, or Retriever-specific metadata (citation URL, highlights, timestamps, ACL flags, per-field scores — anything the Retriever stuffed into metadata).
            texts string[] — parallel array of documents[i].content in the same order. Wire this into AI ops that take string[] (AISummarizeOp, AIRerankOp, AIBestMatchOp candidates).
  Setup is fail-fast: if no Retriever is registered the graph errors before any vertex runs. Call setDefaultRetriever (or registerRetriever) before running the graph. The credential options are installed on the retrieval context and consumed by user Retrievers via resolveEmbeddingClient — omit them for Retrievers that don't embed (BM25, hosted search with its own auth, etc.).`;

export const RetrieveWithFiltersOpDescription = `RetrieveWithFiltersOp: like RetrieveOp but with filters that scope the retrieval. Filters may come from a runtime filters input (values produced by upstream graph ops — tenant id from an auth step, category from a classifier, date range from a planner), from a compile-time staticFilters option (values known when the graph is wired — a hardcoded tenant id, a fixed locale), or both.
  Options:  k number — number of documents to return (default 5).
            retrieverId string — selects a Retriever registered via registerRetriever (default "" → process default).
            credentialRef string — opaque credential identifier installed on the retrieval context for the Retriever (default ""; consumed by vector-store-backed Retrievers via resolveEmbeddingClient; ignored by Retrievers that don't embed). credentialRef is a LOOKUP REFERENCE (e.g. an env-var name like "CLAUDE_API_KEY" or a factory key like "voyage-prod") that a registered EmbeddingClientFactory translates into a real credential — it is NOT the secret value itself. Never put an API key, OAuth token, vault URL, or any other secret material as the credentialRef value: such values would land verbatim in your committed source, get pushed to git, and end up indexed by every tool that reads the repo.
            clientFactoryId string — selects a registered EmbeddingClientFactory by id for the Retriever's embedding lookup (default "" → process default set via setDefaultEmbeddingClientFactory). NOTE: the bundled EnvEmbeddingClientFactory only supports provider="gemini". For any other embedding provider (Claude, OpenAI, Voyage, Cohere, …) you MUST register a custom factory via registerEmbeddingClientFactory (or setDefaultEmbeddingClientFactory) before running the graph — the default rejects unknown providers with an error. This is asymmetric with AI ops, whose bundled EnvAIClientFactory supports both Claude and Gemini.
            factoryTimeoutMs number — deadline for the EmbeddingClientFactory credential lookup in milliseconds (default 30000; 0 disables). Bounds the factory's credential-lookup leg only (Vault / Secrets Manager / KMS round trip); the subsequent Retriever.retrieve call is NOT covered by this budget.
            embedTimeoutMs number — wallclock deadline applied to the ENTIRE Retriever.retrieve call in milliseconds (embedding API call + vector search + post-filtering — whatever the Retriever does end-to-end). undefined / 0 = no per-op deadline (the call honors only the ambient signal). Wraps the retrieve invocation with an abort deadline; when it fires, the op returns the wrapped timeout error. Complementary to factoryTimeoutMs.
            staticFilters Record<string, string> — filters known at graph-build time (e.g. { tenant: "acme", locale: "en" }). Merged into the filter map every call. Default {} = no static filters. Use this when filter values are fixed for the lifetime of the program; use the filters input for values computed upstream; supply both to combine them. When both staticFilters is unset AND the filters input is empty/disconnected, the op retrieves without filters.
  Input:    query string — the natural-language search query.
            filters Record<string, string> — optional request-scoped filters. May be omitted when staticFilters is set. When supplied, the map is merged on top of staticFilters every call (runtime wins on key collision). An empty or absent runtime map is treated as "no runtime filters" and falls through to staticFilters. The merged map is installed on the RetrievalContext; the Retriever reads it via RetrievalContext.filters. Values are strings by convention — Retriever implementations parse numbers, split CSV lists, etc.
  Output:   documents Document[] — full records ({ id, content, score, metadata }) sorted best-first.
            texts string[] — parallel array of documents[i].content.
  Use this op when at least one filter value is needed; use plain RetrieveOp when no filters are needed. Retriever implementations that don't understand the filter keys must ignore them, not error. Embedding credentials install on the retrieval context alongside the filters; both values coexist.`;

export const ValidateCitationsOpDescription = `ValidateCitationsOp: filters LLM-emitted citations against an allow-list of source identifiers — a security control. Hallucinated source names (anything the model invents or imports from its training corpus) are dropped; only entries that exactly match a member of the allow-list survive into accepted. Use this op to enforce citation integrity at the boundary between an untrusted AI op and a downstream surface (UI, audit log, database write).
  Input:    raw string[] — the citations parsed out of the model's response (typically the sources produced by your example's parseCitations step over the AI op's raw output). Order is preserved into accepted / rejected.
            allowed string[] — the allow-list of source identifiers the model was permitted to cite. The canonical pattern is: pipe the retrieved Document[] (from RetrieveOp or RetrieveWithFiltersOp) into a sources-extraction step that emits string[] of identifiers (e.g. each document's metadata[MetadataSource]), then wire that string[] here. Build the allow-list from the documents the model actually saw, NOT from the full loaded corpus — a model that hallucinates the filename of a real-but-unretrieved document would otherwise slip past the check.
  Output:   accepted string[] — citations from raw that appear in allowed. De-duplicated (a model that repeats the same source twice yields one accepted entry) and ordered by first appearance in raw.
            rejected string[] — citations from raw that do NOT appear in allowed. De-duplicated and ordered by first appearance in raw. Surface these as a warning (not an error) for observability — they are signal about model behavior, not graph failure.
  Membership is an exact string match against the allowed set; no normalization, no case-folding, no whitespace trimming (upstream parsing is expected to trim already). Empty raw -> both outputs empty. Empty allowed with non-empty raw -> every citation rejected. This is a pure deterministic op (no I/O, no parsing) and never throws.
  WARNING: this op is the right place to enforce citation integrity. Do NOT route unfiltered citations (the raw input, or parseCitations output upstream of this op) to user-facing surfaces, audit logs, or downstream tooling where they will be treated as trustworthy — ALWAYS route the accepted output instead, and warn on the rejected output.`;
