/**
 * Verbatim catalog descriptions for the Retrieval group, ported 1:1 from
 * sparsi-go's retrieve_op.go, retrieve_with_filters_op.go, and
 * validate_citations_op.go. These strings are documentation surfaced by
 * AllDescriptions / LibraryScanOp; the PORT_PROMPT requires exact wording, so
 * they are reproduced as-is (including Go-side references like `config.Params`
 * and `library.RegisterRetriever` — the catalog describes the library's
 * capabilities, and is kept faithful to the Go original). The TS ops expose the
 * same capability through typed options (see retrieve.ts).
 */

export const RetrieveOpDescription = `RetrieveOp: pulls the top-k documents most relevant to a query from a registered Retriever (RAG fan-in).
  Params:   k string — number of documents to return (default "5"). Lower values keep prompts compact; higher values broaden recall.
            retriever_id string — selects a Retriever registered via library.RegisterRetriever (default "" → process default set via library.SetDefaultRetriever).
            credential_ref string — opaque credential identifier installed into ctx for the Retriever (default ""; consumed by library.ResolveEmbeddingClient inside vector-store-backed Retrievers; ignored by Retrievers that don't embed). credential_ref is a LOOKUP REFERENCE (e.g. an env-var name like "CLAUDE_API_KEY" or a factory key like "voyage-prod") that a registered EmbeddingClientFactory translates into a real credential — it is NOT the secret value itself. Never put an API key, OAuth token, vault URL, or any other secret material as the credential_ref value in vertex params: those values land verbatim in the generated main.go, get committed to git, and end up indexed by every tool that reads the repo.
            client_factory_id string — selects a registered EmbeddingClientFactory by id for the Retriever's embedding lookup (default "" → process default set via library.SetDefaultEmbeddingClientFactory). NOTE: the bundled EnvEmbeddingClientFactory only supports provider="gemini". For any other embedding provider (Claude, OpenAI, Voyage, Cohere, …) you MUST register a custom factory via library.RegisterEmbeddingClientFactory (or library.SetDefaultEmbeddingClientFactory) before engine.Run — the default rejects unknown providers with an error. This is asymmetric with AI ops, whose bundled EnvAIClientFactory supports both Claude and Gemini.
            api_factory_timeout_ms string — deadline for the EmbeddingClientFactory credential lookup in milliseconds (default "30000"; "0" disables). Bounds the factory's credential-lookup leg only (Vault / Secrets Manager / KMS round trip); the subsequent Retriever.Retrieve call is NOT covered by this budget. Mirrors AIClientFactory's api_factory_timeout_ms.
            embed_timeout_ms string — wallclock deadline applied to the ENTIRE Retriever.Retrieve call in milliseconds (embedding API call + vector search + post-filtering — whatever the Retriever does end-to-end). Default "" / "0" = no per-op deadline (the call honors only the ambient ctx). Wraps the Retrieve invocation with context.WithTimeout; when it fires, the op returns the wrapped error and the underlying ctx.DeadlineExceeded. Complementary to api_factory_timeout_ms: factory_timeout caps the credential lookup, embed_timeout caps the actual retrieval work.
  Inputs:   Query *string — the natural-language search query.
  Outputs:  Documents []library.Document — full records ({ID, Content, Score, Metadata}) sorted best-first. Use when downstream ops need IDs, scores, or Retriever-specific metadata (citation URL, highlights, timestamps, ACL flags, per-field scores — anything the Retriever stuffed into Metadata).
            Texts []string — parallel slice of Documents[i].Content in the same order. Wire this into AI ops that take *[]string (AISummarizeOp, AIRerankOp, AIBestMatchOp candidates).
  Setup is fail-fast: if no Retriever is registered the graph errors before any vertex runs. Call SetDefaultRetriever (or RegisterRetriever) before engine.Run. The three credential params are installed into ctx via library.WithEmbeddingCredentials and consumed by user Retrievers via library.ResolveEmbeddingClient — omit them for Retrievers that don't embed (BM25, hosted search with its own auth, etc.).`;

export const RetrieveWithFiltersOpDescription = `RetrieveWithFiltersOp: like RetrieveOp but with filters that scope the retrieval. Filters may come from a runtime Filters input wire (values produced by upstream graph ops — tenant id from an auth step, category from a classifier, date range from a planner), from a compile-time static_filters param (values known when the graph is wired — a hardcoded tenant id, a fixed locale), or both.
  Params:   k string — number of documents to return (default "5").
            retriever_id string — selects a Retriever registered via library.RegisterRetriever (default "" → process default).
            credential_ref string — opaque credential identifier installed into ctx for the Retriever (default ""; consumed by library.ResolveEmbeddingClient inside vector-store-backed Retrievers; ignored by Retrievers that don't embed). credential_ref is a LOOKUP REFERENCE (e.g. an env-var name like "CLAUDE_API_KEY" or a factory key like "voyage-prod") that a registered EmbeddingClientFactory translates into a real credential — it is NOT the secret value itself. Never put an API key, OAuth token, vault URL, or any other secret material as the credential_ref value in vertex params: those values land verbatim in the generated main.go, get committed to git, and end up indexed by every tool that reads the repo.
            client_factory_id string — selects a registered EmbeddingClientFactory by id for the Retriever's embedding lookup (default "" → process default set via library.SetDefaultEmbeddingClientFactory). NOTE: the bundled EnvEmbeddingClientFactory only supports provider="gemini". For any other embedding provider (Claude, OpenAI, Voyage, Cohere, …) you MUST register a custom factory via library.RegisterEmbeddingClientFactory (or library.SetDefaultEmbeddingClientFactory) before engine.Run — the default rejects unknown providers with an error. This is asymmetric with AI ops, whose bundled EnvAIClientFactory supports both Claude and Gemini.
            api_factory_timeout_ms string — deadline for the EmbeddingClientFactory credential lookup in milliseconds (default "30000"; "0" disables). Bounds the factory's credential-lookup leg only (Vault / Secrets Manager / KMS round trip); the subsequent Retriever.Retrieve call is NOT covered by this budget.
            embed_timeout_ms string — wallclock deadline applied to the ENTIRE Retriever.Retrieve call in milliseconds (embedding API call + vector search + post-filtering — whatever the Retriever does end-to-end). Default "" / "0" = no per-op deadline (the call honors only the ambient ctx). Wraps the Retrieve invocation with context.WithTimeout; when it fires, the op returns the wrapped error and the underlying ctx.DeadlineExceeded. Complementary to api_factory_timeout_ms.
            static_filters string — comma-separated key=value pairs of filters known at graph-build time (e.g. "tenant=acme,locale=en"). Parsed at Setup and merged into the filter map every Run. Default "" = no static filters. Malformed entries (no "=", empty key, duplicate key) fail at Setup. Use this when filter values are fixed for the lifetime of the program; use the Filters wire for values computed upstream; supply both to combine them. When both static_filters is unset AND the Filters wire is empty/disconnected at Run, the op logs a WARN and retrieves without filters.
  Inputs:   Query *string — the natural-language search query.
            Filters *map[string]string — optional request-scoped filters. May be left disconnected when static_filters is set. When connected, the map is merged on top of static_filters every Run (runtime wins on key collision). Empty or nil runtime map is treated as "no runtime filters" and falls through to static_filters. The merged map is installed into ctx via library.WithRetrievalFilters; the Retriever reads it via library.RetrievalFiltersFromContext. Values are strings by convention — Retriever implementations parse numbers, split CSV lists, etc.
  Outputs:  Documents []library.Document — full records ({ID, Content, Score, Metadata}) sorted best-first.
            Texts []string — parallel slice of Documents[i].Content.
  Use this op when at least one filter value is needed; use plain RetrieveOp when no filters are needed. Retriever implementations that don't understand the filter keys must ignore them, not error. Embedding credentials install into ctx alongside the filters; both values coexist.`;

export const ValidateCitationsOpDescription = `ValidateCitationsOp: filters LLM-emitted citations against an allow-list of source identifiers — a security control. Hallucinated source names (anything the model invents or imports from its training corpus) are dropped; only entries that exactly match a member of the allow-list survive into Accepted. Use this op to enforce citation integrity at the boundary between an untrusted AI op and a downstream surface (UI, audit log, database write).
  Inputs:   Raw *[]string — the citations parsed out of the model's response (typically the Sources slice produced by your example's ParseCitations step over the AI op's raw output). Order is preserved into Accepted / Rejected.
            Allowed *[]string — the allow-list of source identifiers the model was permitted to cite. The canonical pattern is: pipe the retrieved []library.Document slice (from RetrieveOp or RetrieveWithFiltersOp) into a sources-extraction step that emits []string of identifiers (e.g. each Document's Metadata[library.MetadataSource]), then wire that []string here. Build the allow-list from the documents the model actually saw, NOT from the full loaded corpus — a model that hallucinates the filename of a real-but-unretrieved document would otherwise slip past the check.
  Outputs:  Accepted []string — citations from Raw that appear in Allowed. De-duplicated (a model that repeats the same source twice yields one Accepted entry) and ordered by first appearance in Raw.
            Rejected []string — citations from Raw that do NOT appear in Allowed. De-duplicated and ordered by first appearance in Raw. Surface these via slog at Warn (not Error) for observability — they are signal about model behavior, not graph failure.
  Membership is an exact string match against the Allowed set; no normalization, no case-folding, no whitespace trimming (upstream parsing is expected to trim already). Nil/empty Raw -> both outputs empty. Nil/empty Allowed with non-empty Raw -> every citation rejected. Run never returns an error; this is a pure deterministic op (no I/O, no parsing).
  WARNING: this op is the right place to enforce citation integrity. Do NOT route unfiltered citations (the Raw input, or ParseCitations output upstream of this op) to user-facing surfaces, audit logs, or downstream tooling where they will be treated as trustworthy — ALWAYS route the Accepted output instead, and slog-warn the Rejected output.`;
